#!/bin/sh /etc/rc.common
# Move 2.4GHz and 5GHz Wi-Fi to CPU1 and CPU2

START=99

start() {
        mask=2

        for irq in $(grep "mt76..e" /proc/interrupts | cut -d: -f1 | sed 's, *,,')
        do
                echo "$mask" > "/proc/irq/$irq/smp_affinity"
                [ $mask = 2 ] && mask=4
        done
}